### ISSUE TITLE
kernels within kernels

### ISSUE THREAD

**Issue by aespielberg** [yuanming-hu/taichi#278]
I have two kernels for a neural network, nn1 and nn2.

I try the following code, inside a class:

```
@ti.classkernel
def nn(self, t: ti.i32):
    self.nn1(t)
    self.nn2(t)
```

Their signatures:

```
@ti.classkernel
  def nn1(self, t: ti.i32):
```

```
@ti.classkernel
  def nn2(self, t: ti.i32):
```
```

Calling this kernel, though, gives the following error:


Traceback (most recent call last):
  File "test_mpm_simulator.py", line 113, in main
    sim.forward(sim.steps)
  File "/home/aespielberg2/ResearchCode/KnittableRobotsSIG2020/mpm_simulator.py", line 594, in forward
    self.advance(s)
  File "/home/aespielberg2/anaconda3/lib/python3.7/site-packages/taichi/lang/__init__.py", line 128, in decorated
    raise e
  File "/home/aespielberg2/anaconda3/lib/python3.7/site-packages/taichi/lang/__init__.py", line 126, in decorated
    func(*args, **kwargs)
  File "/home/aespielberg2/ResearchCode/KnittableRobotsSIG2020/mpm_simulator.py", line 551, in advance
    self.nn(s)
  File "/home/aespielberg2/anaconda3/lib/python3.7/site-packages/taichi/lang/kernel.py", line 275, in decorated
    primal(*args, **kwargs)
  File "/home/aespielberg2/anaconda3/lib/python3.7/site-packages/taichi/lang/kernel.py", line 256, in __call__
    self.materialize(key=key, args=args)
  File "/home/aespielberg2/anaconda3/lib/python3.7/site-packages/taichi/lang/kernel.py", line 194, in materialize
    taichi_kernel = taichi_kernel.define(lambda: compiled())
  File "/home/aespielberg2/anaconda3/lib/python3.7/site-packages/taichi/lang/kernel.py", line 194, in <lambda>
    taichi_kernel = taichi_kernel.define(lambda: compiled())
  File "/home/aespielberg2/ResearchCode/KnittableRobotsSIG2020/mpm_simulator.py", line 202, in nn
    self.nn1(t)
  File "/home/aespielberg2/anaconda3/lib/python3.7/site-packages/taichi/lang/kernel.py", line 275, in decorated
    primal(*args, **kwargs)
  File "/home/aespielberg2/anaconda3/lib/python3.7/site-packages/taichi/lang/kernel.py", line 256, in __call__
    self.materialize(key=key, args=args)
  File "/home/aespielberg2/anaconda3/lib/python3.7/site-packages/taichi/lang/kernel.py", line 194, in materialize
    taichi_kernel = taichi_kernel.define(lambda: compiled())
  File "/home/aespielberg2/anaconda3/lib/python3.7/site-packages/taichi/lang/kernel.py", line 194, in <lambda>
    taichi_kernel = taichi_kernel.define(lambda: compiled())
  File "/home/aespielberg2/ResearchCode/KnittableRobotsSIG2020/mpm_simulator.py", line 206, in nn1
    @ti.classkernel
NameError: name 'ti' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_mpm_simulator.py", line 138, in <module>
    main()
  File "test_mpm_simulator.py", line 113, in main
    sim.forward(sim.steps)
  File "/home/aespielberg2/anaconda3/lib/python3.7/site-packages/taichi/lang/tape.py", line 21, in __exit__
    self.grad()
  File "/home/aespielberg2/anaconda3/lib/python3.7/site-packages/taichi/lang/tape.py", line 32, in grad
    func.grad(*args)
  File "/home/aespielberg2/anaconda3/lib/python3.7/site-packages/taichi/lang/__init__.py", line 138, in decorated
    func(*args, **kwargs)
  File "/home/aespielberg2/ResearchCode/KnittableRobotsSIG2020/mpm_simulator.py", line 580, in advance_grad
    self.nn(s, __gradient=True)
  File "/home/aespielberg2/anaconda3/lib/python3.7/site-packages/taichi/lang/kernel.py", line 273, in decorated
    adjoint(*args, **kwargs)
  File "/home/aespielberg2/anaconda3/lib/python3.7/site-packages/taichi/lang/kernel.py", line 256, in __call__
    self.materialize(key=key, args=args)
  File "/home/aespielberg2/anaconda3/lib/python3.7/site-packages/taichi/lang/kernel.py", line 194, in materialize
    taichi_kernel = taichi_kernel.define(lambda: compiled())
  File "/home/aespielberg2/anaconda3/lib/python3.7/site-packages/taichi/lang/kernel.py", line 194, in <lambda>
    taichi_kernel = taichi_kernel.define(lambda: compiled())
  File "/home/aespielberg2/ResearchCode/KnittableRobotsSIG2020/mpm_simulator.py", line 202, in nn
    self.nn1(t)
  File "/home/aespielberg2/anaconda3/lib/python3.7/site-packages/taichi/lang/kernel.py", line 275, in decorated
    primal(*args, **kwargs)
  File "/home/aespielberg2/anaconda3/lib/python3.7/site-packages/taichi/lang/kernel.py", line 257, in __call__
    return self.compiled_functions[key](*args)
  File "/home/aespielberg2/anaconda3/lib/python3.7/site-packages/taichi/lang/kernel.py", line 219, in func__
    raise KernelArgError(i, needed, provided)
taichi.lang.kernel.KernelArgError: (1, DataType.int32, <class 'taichi.lang.expr.Expr'>)

```

**Comment by aespielberg** [comment]
I should note I have also tried making this a complex kernel and writing out the grad for nn, but that doesn't work either.

**Comment by yuanming-hu** [comment]
Hi Andy,

Kernel inside kernel is not supported. However, you can just use a normal
python function for the outer kernel.

**Comment by aespielberg** [comment]
Thanks!  How do I know when to use a kernel or not a kernel?

**Comment by aespielberg** [comment]
I just tested nn, declaring it as not a kernel, and I get the same error, unfortunately:

Traceback (most recent call last):
  File "test_mpm_simulator.py", line 138, in <module>
    main()
  File "test_mpm_simulator.py", line 113, in main
    sim.forward(sim.steps)
  File "/home/aespielberg2/ResearchCode/KnittableRobotsSIG2020/mpm_simulator.py", line 594, in forward
    self.advance(s)
  File "/home/aespielberg2/anaconda3/lib/python3.7/site-packages/taichi/lang/__init__.py", line 128, in decorated
    raise e
  File "/home/aespielberg2/anaconda3/lib/python3.7/site-packages/taichi/lang/__init__.py", line 126, in decorated
    func(*args, **kwargs)
  File "/home/aespielberg2/ResearchCode/KnittableRobotsSIG2020/mpm_simulator.py", line 554, in advance
    self.nn(s)
  File "/home/aespielberg2/ResearchCode/KnittableRobotsSIG2020/mpm_simulator.py", line 201, in nn
    self.nn1(t)
  File "/home/aespielberg2/anaconda3/lib/python3.7/site-packages/taichi/lang/kernel.py", line 275, in decorated
    primal(*args, **kwargs)
  File "/home/aespielberg2/anaconda3/lib/python3.7/site-packages/taichi/lang/kernel.py", line 256, in __call__
    self.materialize(key=key, args=args)
  File "/home/aespielberg2/anaconda3/lib/python3.7/site-packages/taichi/lang/kernel.py", line 194, in materialize
    taichi_kernel = taichi_kernel.define(lambda: compiled())
  File "/home/aespielberg2/anaconda3/lib/python3.7/site-packages/taichi/lang/kernel.py", line 194, in <lambda>
    taichi_kernel = taichi_kernel.define(lambda: compiled())
  File "/home/aespielberg2/ResearchCode/KnittableRobotsSIG2020/mpm_simulator.py", line 211, in nn1
    @ti.classkernel
NameError: name 'ti' is not defined

**Comment by yuanming-hu** [comment]
Could you share with me a commit it to reproduce this? I have to catch a flight in 5 minutes but will take a look once I reach my destination.

**Comment by aespielberg** [comment]
Will do shortly.

**Comment by aespielberg** [comment]
Current commit in my other repo.

**Comment by yuanming-hu** [comment]
Sorry about the delay. It's sad that fully fixing this requires digging into the internal implementation of the python interpreter; I pushed a temporary fix for this specific case: just avoid indirect function calls when launching kernels.

**Comment by yuanming-hu** [comment]
Merged into #282

**Comment by yuanming-hu** [comment]
After diving into the Python data model (https://docs.python.org/3.6/reference/datamodel.html), this is systematically resolved in v0.1.5.

**Comment by aespielberg** [comment]
Thank you!  Just to be clear, kernels within kernels are still not
supported, right?  But otherwise things should be okay?  What caused this
error to begin with?

**Comment by yuanming-hu** [comment]
No, that will not be supported. The error is caused by some variable resolution issues due to the heavy use of metaprogramming in the Taichi compiler.

**Comment by aespielberg** [comment]
Gotcha.  Okay, thank you!

**Comment by aespielberg** [comment]
What was the fix, exactly?  Because I am still having the same issue in my code after updating.

**Comment by aespielberg** [comment]
For some reason doing it like this takes forever to compile now.  Any idea as to why?
